### ISSUE TITLE
Regexp

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/properties#102]
Can we add something like regexp to the strings? Similar to how we can bound floats with min/max.

```python
email = properties.String("The users email", regexp=r".+\@.+\..+", strip=" ")
```

**Comment by bsmithyman** [comment]
Should we consider making this a subclass, or do you think it should be built into the base `String`?

**Comment by fwkoch** [comment]
This sounds good to me. Off the top of my head, I don't see any reason not to add this as part of the base `String` - default can be `None`. @bsmithyman - do you see a case for subclassing instead?

**Comment by bsmithyman** [comment]
@fwkoch: Not necessarily, unless to keep the basic API as simple as possible and move this into an added-features pack like the image / math stuff. That said, `re` is in the standard library, so I see no reason not to just include this in the base string. It would also then make it very, very straightforward for users to subclass `String` to make things like an `EmailAddress` property that had a hard-coded regex.

Had wondered about a URL property as well, which could make use of this.

**Comment by fwkoch** [comment]
This is tackled in #117
