### ISSUE TITLE
properties.Array validation numpy arrays full of objects, e.g. strings

### ISSUE THREAD

**Issue by ThomasMatern** [3ptscience/properties#106]
The validation only matches the types defined in `TYPE_MAPPINGS` against the allowed types in `Array.dtype`

When passing in a numpy array with `dtype=='O'`, the validation passes (but the serialization fails).

The validation should fail.

**Comment by fwkoch** [comment]
Rather than modifying TYPE_MAPPINGS, I modified validation logic: https://github.com/3ptscience/properties/pull/107

**Comment by fwkoch** [comment]
Thanks @ThomasMatern - this has been fixed with #107.
