### ISSUE TITLE
Improve doc formatting of properties

### ISSUE THREAD

**Issue by fwkoch** [3ptscience/properties#110]
The auto-generated docs are starting to look a bit messy using Sphinx built in property/attribute tags. It is strange that "Required" and "Parameters" are on different lines, then the immutable "attributes" are formatted differently (see screenshot below). I think we need some more customized formatting that doesn't use the builtin property/attribute tags.

<img width="811" alt="screen shot 2016-12-09 at 8 58 10 am" src="https://cloud.githubusercontent.com/assets/9453731/21056421/c6b0348e-bdf2-11e6-95f1-aaa92aef084f.png">

**Comment by bsmithyman** [comment]
Yeah, that is a lot more streamlined and consistent. Nice.

**Comment by fwkoch** [comment]
See #119
