### ISSUE TITLE
Load from state should not send changes

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/properties#113]
When loading a properties class from a pickle or json it should not send incremental change notifications as the state may not be correct until the end of the load.

Do we have the idea of `hold_notifications`?

**Comment by fwkoch** [comment]
We only have this idea when `reset`ing to default values (or initially setting the default values), but `hold_notifications` doesn't exist as a standalone concept yet. It certainly should!

**Comment by bsmithyman** [comment]
Slightly related question:
If loading from state potentially means loading from an old pickle, do we still do the usual validation at the end of the load? I can see cases where we wouldn't want to skip validation, though of course holding it for the end is very useful. Or, is it useful to be able to pickle invalid `HasProperties` instances?

**Comment by fwkoch** [comment]
I think pickling/unpickling invalid instances may be ok. `Property` class validation will still happen (ie String is still String). Only the extra `HasProperties` validators won't fire. I don't think it's `properties`'s jurisdiction to stop loading of an invalid class (it got to that state somehow...). Maybe we could display a warning if invalid...?

However, this maybe brings up a further question - should change validators fire on `validate` as well... (in addition to class validators)? If so, or even if we fire validators at the end of loading a pickle, there needs to be some more documentation on ensuring validators will work as expected regardless of state, order they are called in, etc.

**Comment by bsmithyman** [comment]
Yeah, I guess I wonder if it is straightforward to detect invalid pickles; it got to that state somehow, but what if that state is not actually okay for the current code (e.g., it got to that state by being saved to a pickle from a version of the code that is not forwards-compatible, or even from a newer version that is not backwards-compatible).

**Comment by fwkoch** [comment]
Hard to say - unpickling will fail if attribute doesn't exist on the class anymore or value is invalid for the property. If a pickle passes those (but is invalid for some other reason, eg validators fail) maybe we should allow it to load, then be corrected by the user. Similarly, maybe someone wants to save a `SimPEG` workspace filled with `HasProperties` instances they are working on. These may be invalid, but it would be nice to be able to save/load as-is.

There is certainly arguments for not allowing this - security, shipping off a pickle to be used elsewhere and assuming it will work, etc... But my thought is those cases call for serialization. Possibly with kwarg `allow_invalid=False` or something. Pickling should be as generous, unconstrained, insecure, etc. as possible (in my opinion - certainly flexible).

**Comment by fwkoch** [comment]
Listeners are disabled during deserialization (see #123). We still don't have the idea of holding notifications and firing them all after the state is set. See #138
