### ISSUE TITLE
Other repos/research

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/properties#135]
There are a couple other repos and research that I wanted to share.

Both of these have a scientific bent to them, units and scipy stack (neither seems heavily maintained at the moment):
https://github.com/astrofrog/numtraits
https://github.com/jupyter-incubator/traittypes

This makes use of `astropy.units`:

![image](https://cloud.githubusercontent.com/assets/913249/22913832/5f6fd2a4-f22a-11e6-9c92-9f7ef9b53903.png)

There is also now some way to do this without meta classes, but this seems unnecessary at the moment:
https://www.python.org/dev/peps/pep-0487

Added to readme, but you can probably kill PR#134

**Comment by rowanc1** [comment]
Also came across Param:

http://ioam.github.io/param/

Seems to be used by `paramnb` and `holoviews`.

**Comment by fwkoch** [comment]
Much more documentation on other repos has been added here: 

https://github.com/3ptscience/properties/pull/154
