### ISSUE TITLE
copy on HasProperties 

### ISSUE THREAD

**Issue by lheagy** [3ptscience/properties#143]
I am inheriting `HasProperties` to generate a simple class (https://github.com/lheagy/casingResearch/blob/master/casingSimulations/model.py#L16) and would like to have a `copy` method.  What I am doing right now is 

```
    def copy(self):
        """
        Make a copy of the current CasingParameters object
        """
        return CasingParameters.deserialize(self.serialize())
```

I would see this being useful functionality on the base `HasProperties` class (unless you have something similar already?)

**Comment by fwkoch** [comment]
Thanks - this has come up before, and my solution was exactly the same as yours; there isn't anything else similar built in. I agree this would be good functionality to add.

**Comment by fwkoch** [comment]
added with #147
