### ISSUE TITLE
Required and default

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/properties#44]
Currently the functionality rejects setting default required properties. This should be rethought.

**Comment by fwkoch** [comment]
I removed the code that prevented defaults on required properties. `assert_valid` now raises an error if the property is required and the value is `None` or `undefined` (rather than just `None` as before). Does this seem sufficient?

**Comment by fwkoch** [comment]
https://github.com/3ptscience/properties/commit/492417ef2abf6bb23de9dfa9f42ace6b163cf5d6

**Comment by fwkoch** [comment]
See the commit above. Merging #61 locked this down.
