### ISSUE TITLE
StringChoices should accept a set for choices

### ISSUE THREAD

**Issue by bsmithyman** [3ptscience/properties#51]
We are requiring that the user pass a `list` or `tuple` here (or a `dict`). However, we are using it like a `set`. At the least, we should accept a set. In some ways, I would prefer that we handle this in a way that does not require direct inheritance from `set`, `list`, `tuple` or `dict`, but rather uses ABCs.

**Comment by fwkoch** [comment]
StringChoices now accept sets. There is also more validation in place to ensure all the choices are unique.
