### ISSUE TITLE
Unicode support for string property

### ISSUE THREAD

**Issue by fwkoch** [3ptscience/properties#57]
`String` properties should work with unicode in Python 2 and 3.

**Comment by lxop** [comment]
The test suite should also be extended to include interesting unicode strings

**Comment by fwkoch** [comment]
String properties now have a `unicode` attribute. By default this is `True` and all strings are coerced to unicode. If `False`, the original type of string will be preserved.

Casting to `str` has been totally removed in favour of python 2/3 compatible types.
