### ISSUE TITLE
Float validation is broken

### ISSUE THREAD

**Issue by ThomasMatern** [3ptscience/properties#71]
I've noticed this because we accidentally tried to build a Colour Legend from a list of float tuples. The float tuples did not pass the Colour validation (good) but they passed the Float validation (bad).
So, passing a tuple of floats into a Float passes the validation, but it should not.
The validator checks if the value is of type (float, integer_types) but it does not raise an exception if this fails. The following in_bounds check is skipped if the Float has no min/max values set.

**Comment by fwkoch** [comment]
Thanks for catching this oversight! This has been addressed in the latest pull request (see here: https://github.com/3ptscience/properties/pull/69/files#diff-5570cf7567380218e7577d8336538325R389). Now we insure the coerced value is a `float` - that should eliminate tuples from passing.

**Comment by fwkoch** [comment]
Fixed on this commit: https://github.com/3ptscience/properties/commit/4f732ebea7e45a4224fa371fb7aece142b678535

Now on `dev`.
