### ISSUE TITLE
Bool Array

### ISSUE THREAD

**Issue by lheagy** [3ptscience/properties#77]
Right now Arrays are restricted to floats and ints. Could this be extended to include bools as well? eg
```
import numpy as np
np.array(np.ones(4), dtype=bool)
```
or perhaps a separate BoolArray class?

**Comment by fwkoch** [comment]
Yes, adding `bool` as an allowed type makes sense and should be straightforward.

**Comment by fwkoch** [comment]
This has been merged to dev here: https://github.com/3ptscience/properties/pull/83
