### ISSUE TITLE
Revisiting numpy dependency

### ISSUE THREAD

**Issue by bsmithyman** [3ptscience/properties#78]
@fwkoch, @varyag00, @rowanc1: What are your thoughts on the viability of removing the `numpy` dependency from `properties` and putting it in something like `properties_array`? The `numpy` dependency is a major deployment hurdle for lightweight web environments.

Thanks!

**Comment by fwkoch** [comment]
Sounds like a pretty good idea - `array` is already built with easily swappable `wrapper`. I could see changing the default wrapper to `list` (or `tuple` or something), but make `np.ndarray` easy to opt into (maybe through `properties_math`? or maybe a different solution?).

**Comment by fwkoch** [comment]
@bsmithyman Let me know what you think of this PR: https://github.com/3ptscience/properties/pull/84

- Array is now moved to `math.py`.
- Other basic properties don't depend on numpy any more.
- math properties are only imported if `numpy` and `vectormath` are available.
- `pip install properties` does NOT install numpy (or vectormath), you must explicitly `pip install properties[math]`
- A similar framework can now be used for image properties. ie `pip install properties[image]` also installs `pypng` allowing `ImagePNG` to be imported
- For a full installation of all available properties, `pip install properties[full]`

**Comment by bsmithyman** [comment]
That is super cool. Just looking at how it works now.

**Comment by bsmithyman** [comment]
https://github.com/3ptscience/properties/pull/84
