### ISSUE TITLE
Consider modifying HasProperties instance setup

### ISSUE THREAD

**Issue by fwkoch** [3ptscience/properties#85]
When overriding `__init__` in HasProperties classes, `super` must be called first. This is a bit unintuitive and perhaps can be fixed by doing some setup in `__new__` instead?

**Comment by bsmithyman** [comment]
If we want people to be able to change the initialization signature that will be pretty limited, since so much is tweaked by the metaclass. What's your thinking?

**Comment by fwkoch** [comment]
Hm, yeah I thought about this a bit more and I think it's best to just leave as-is. Overriding `__init__` is ok as long as `super().__init__` is the first thing that is called. This is actually really useful for `Instance` property coercion where input values (if not an instance of the correct type) are passed to the constructor:

```
import numpy as np
import properties

class WrappedArray(properties.HasProperties):
    array = properties.Array('wrapped array')
    description = properties.String('description of the array')
    def __init__(self, arr=None, **kwargs):
        super(WrappedArray, self).__init__(**kwargs)
        if arr is not None:
            self.array = arr

class HasWrappedArray(properties.HasProperties):
    array = properties.Instance('the wrapped array', WrappedArray)

hwa = HasWrappedArray()
hwa.array = np.ones(100)
assert isinstance(hwa.array, WrappedArray)
```

I think really the only takeaway here is we need documentation that subclasses must call the HasProperties init first.

**Comment by fwkoch** [comment]
After talking with @bsmithyman about this a bit more - We could do some of the instance setup in `PropertyMetaclass` `__call__` - that has access to the instance before calling init. Here, we can set the backend, add the listeners and set the defaults, then pass off to `__init__` for setting kwargs.

**Comment by fwkoch** [comment]
The above commit contains implementation described in the previous comment.
